### API

: 어떠한 프로그램에서 제공하는 기능을 사용자가 사용 가능하도록 제작한 인터페이스

<br>

### HTTP 프로토콜

:  서로 다른 서버 간에 문자 형식으로 데이터를 주고 받을 때 지켜야 하는 규약

<br>

### 동기와 비동기

: 우리의 운영체제에게 프로세스라고 하는 작업 영역을 할당 받아 어떠한 동작을 수행

**동기**: 하나의 작업이 종료될 때까지 다음 과정이 수행되지 않고 기다리는 방식

**비동기**: 하나의 작업이 진행되면서 다른 작업도 동시에 진행

```
console.log("1")

setTimeout(() => {
    console.log("2")
}, 2000)

console.log("3")
```

: 1과 3이 먼저 출력되고 2초 후 "2"가 출력된다. 왜 그럴까? 

<br>

stack : 먼저 들어온 함수, 데이터가 가장 마지막에 처리됨

queue : 먼저 들어온 함수, 데이터가 가장 먼저 처리됨

<br>

- 기본적인 함수들은 call stack에 쌓인다.
- 비동기 함수들은 모두 callback queue에 쌓인다.
- call stack에 쌓인 함수들은 먼저 담긴 함수들이 위에 쌓인 함수들이 종료될 때까지 기다림.
- callback queue에 쌓인 비동기 함수들은 call stack이 비워져 있을 때 하나씩 옮겨진다.

```
setTimeout(() => {
	console.log("setTimeout call")
})

const func3 = function() {
	console.log("func3 call")
}

const func2 = function() {
	func3()
	console.log("func2 call")
}

const func1 = function() {
	func2()
	console.log("func1 call")
}

func1()
```

: setImeout 함수는 비동기 함수이므로 지연 시간을 지정하지 않아도 callback queue로 옮겨짐

<br>

### Promise 객체

- 비동기 작업을 수행하기 위해 나온 해결책이 callback 함수 (but, 콜백 지옥으로 비효율)

- Promise: 현재 얻지는 못하지만, 추후 작업이 완료된 후 받을 수 있는 데이터에 대한 접근 수단의 역할을 해줌.
- new promise()
- pending : 비동기 처리가 아직 완료되지 않음
- Fulfilled : 비동기 처리가 완료되어 결과값을 반환해준 상태
- Rejected : 비동기 처리가 실패 혹은 오류가 발생한 상태

```
const promiseTest = function(){
	return new Promise ((resolver, reject)=>{
	setTimeout(()=>{
	resolver(100);
	},2000);
	})
}
promiseTest()
```

:promiseTest 함수 실행 시, 반환 값으로 Promise 객체 돌려받는 코드

: 내부함수는 resolver, reject를 매개변수로 받아올 수 있음

:비동기 처리가 완료되면 resolver가 호출됨

:비동기 처리에 실패하면 reject가 호출됨

: reseolver의 실행을 2초간 지연시킨다 -> Promise 객체를 돌려 받은 뒤, 2초가 지나기 전 참조하려고 하면 resolver가 호출되지 않았기 때문에 pending 상태를 받음

<br>

### then(), catch()

- 통신을 통해 답을 받아오는 과정이 코드가 실행되는 과정보다 느림
- 비동기 통신을 처리해주는 방법

```
fetch(HTTP Request).then((res)=>{
	console.log(res)
})
```

:fetch() 사용한 후 그 응답을 받을 때까지 기다리도록 fetch()에 붙여서 then()을 사용해주면 된다.

: then() 메서드 내부에서 익명 함수를 만들어 매개변수로 데이터를 받아올 수가 있다. 받아오는 데이터가 통신의 결과로 우리에게 갔다준 데이터.

:catch()로 error의 내용을 받아올 수 있다.

<br>

<br>

#### 출처 : 인프런 훈훈한 자바스크립트

